### ISSUE TITLE
Linux AppImage doesn't have the LiteOn/Pioneer plugins

### ISSUE THREAD

**Issue by moisespr123** [speed47/qpxtool#31]
Only allows me to choose the benQ and NEC plugins.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
For me the only selectable thing is "Autodetect" when using the appimage under the qScan plugin dropdown. Using HL-DT-ST BH16NS40.

**Comment by speed47** [comment]
Hello,

I can't seem to be able to reproduce your issue, just downloaded the latest AppImage and I see all plugins:

<img width="935" alt="qpxtool_screen" src="https://github.com/speed47/qpxtool/assets/218502/8bb04a10-048d-4b2e-9f9f-e58e010eb6e8">

**Comment by speed47** [comment]
No, that's the AppImage version, running from a Linux server with X forwarding enabled on Windows.

However, I finally can reproduce the problem: the issue is that on my server, I also have qpxtool installed locally, and the problem here is that the AppImage version doesn't look for the plugins in the temporary mount directory but on the local system. This is why it "worked" on my side, but not on yours!

I had to boot a LiveCD to reproduce it and understand what was going on. I have to patch the code so that it looks in the proper directory for the AppImage version

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Thank you very much for your time

**Comment by speed47** [comment]
`pl4` should now work correctly in AppImage mode
